import { defineConfig } from "@playwright/test";

export default defineConfig({
  testDir: "./e2e",
  testMatch: [
    "login-screen.spec.ts",
    "register-screen.spec.ts",
    "invite-screen.spec.ts",
    "dashboard-screen.spec.ts",
    "completeness-screen.spec.ts",
    "projects-screen.spec.ts",
    "project-settings-screen.spec.ts",
    "assignments-screen.spec.ts",
    "users-screen.spec.ts",
    "company-structure-screen.spec.ts",
    "boundaries-screen.spec.ts",
    "boundary-preview-screen.spec.ts",
    "collection-screen.spec.ts",
    "data-entry-screen.spec.ts",
    "evidence-screen.spec.ts",
    "validation-screen.spec.ts",
    "merge-screen.spec.ts",
    "report-audit-screen.spec.ts",
    "admin-settings-screen.spec.ts",
    "notifications-platform-screen.spec.ts",
    "ai-profile-settings-screen.spec.ts",
  ],
  timeout: 120_000,
  fullyParallel: false,
  workers: 1,
  outputDir: "../artifacts/screens/regression/test-results",
  reporter: [
    ["list"],
    ["html", { outputFolder: "../artifacts/screens/regression/playwright-report", open: "never" }],
  ],
  use: {
    baseURL: process.env.PLAYWRIGHT_BASE_URL || "http://localhost:3002",
    browserName: "chromium",
    headless: true,
    screenshot: "only-on-failure",
    trace: "retain-on-failure",
  },
});
