"""add_missing_columns_and_tables

Revision ID: b8cf0807fad2
Revises: 20260325_06
Create Date: 2026-03-25 12:53:01.641440

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b8cf0807fad2"
down_revision: str | None = "20260325_06"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _inspector():
    return sa.inspect(op.get_bind())


def _has_table(table_name: str) -> bool:
    return table_name in _inspector().get_table_names()


def _has_column(table_name: str, column_name: str) -> bool:
    return any(column["name"] == column_name for column in _inspector().get_columns(table_name))


def _has_index(table_name: str, index_name: str) -> bool:
    return any(index["name"] == index_name for index in _inspector().get_indexes(table_name))


def _has_unique_constraint(table_name: str, constraint_name: str) -> bool:
    return any(
        constraint.get("name") == constraint_name
        for constraint in _inspector().get_unique_constraints(table_name)
    )


def _create_table_if_missing(table_name: str, *columns, **kwargs) -> None:
    if not _has_table(table_name):
        op.create_table(table_name, *columns, **kwargs)


def _add_column_if_missing(table_name: str, column: sa.Column) -> None:
    if not _has_column(table_name, column.name):
        op.add_column(table_name, column)


def _create_index_if_missing(table_name: str, index_name: str, columns: list[str]) -> None:
    if not _has_index(table_name, index_name):
        op.create_index(index_name, table_name, columns, unique=False)


def _create_unique_if_missing(table_name: str, constraint_name: str, columns: list[str]) -> None:
    if not _has_unique_constraint(table_name, constraint_name):
        op.create_unique_constraint(constraint_name, table_name, columns)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _create_table_if_missing(
        "platform_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("allow_self_registration", sa.Boolean(), nullable=False),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    _create_table_if_missing(
        "worker_leases",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("owner_id", sa.String(), nullable=False),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status", sa.String(), nullable=True),
        sa.Column("last_result", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    _create_index_if_missing("worker_leases", op.f("ix_worker_leases_expires_at"), ["expires_at"])
    _create_table_if_missing(
        "data_point_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("data_point_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("numeric_value", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("text_value", sa.Text(), nullable=True),
        sa.Column("unit_code", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("changed_by", sa.Integer(), nullable=True),
        sa.Column("change_reason", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["changed_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["data_point_id"], ["data_points.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("data_point_id", "version", name="uq_dp_version"),
    )
    _create_index_if_missing(
        "data_point_versions", op.f("ix_data_point_versions_data_point_id"), ["data_point_id"]
    )
    _add_column_if_missing("ai_interactions", sa.Column("tools_used", sa.String(), nullable=True))
    _add_column_if_missing(
        "data_points",
        sa.Column("is_derived", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    _add_column_if_missing(
        "data_points", sa.Column("calculation_rule_id", sa.Integer(), nullable=True)
    )
    _add_column_if_missing(
        "export_jobs", sa.Column("artifact_encoding", sa.String(), nullable=True)
    )
    _add_column_if_missing(
        "export_jobs",
        sa.Column("attempt", sa.Integer(), nullable=False, server_default=sa.text("0")),
    )
    _add_column_if_missing(
        "export_jobs",
        sa.Column("max_attempts", sa.Integer(), nullable=False, server_default=sa.text("3")),
    )
    _add_column_if_missing(
        "export_jobs", sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True)
    )
    _create_index_if_missing("export_jobs", op.f("ix_export_jobs_next_retry_at"), ["next_retry_at"])
    _add_column_if_missing(
        "notifications",
        sa.Column("digest_sent", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    _add_column_if_missing(
        "notifications", sa.Column("digest_sent_at", sa.DateTime(timezone=True), nullable=True)
    )
    if _has_table("refresh_tokens") and _has_column("refresh_tokens", "rotated_from_id"):
        try:
            op.create_foreign_key(
                None,
                "refresh_tokens",
                "refresh_tokens",
                ["rotated_from_id"],
                ["id"],
                ondelete="SET NULL",
            )
        except Exception:
            pass
    _add_column_if_missing(
        "reporting_projects", sa.Column("boundary_snapshot_id", sa.Integer(), nullable=True)
    )
    if _has_table("reporting_projects") and _has_column(
        "reporting_projects", "boundary_snapshot_id"
    ):
        try:
            op.create_foreign_key(
                None,
                "reporting_projects",
                "boundary_snapshots",
                ["boundary_snapshot_id"],
                ["id"],
                ondelete="SET NULL",
            )
        except Exception:
            pass
    if _has_unique_constraint("requirement_item_shared_elements", op.f("uq_item_shared_element")):
        op.drop_constraint(
            op.f("uq_item_shared_element"), "requirement_item_shared_elements", type_="unique"
        )
    _create_unique_if_missing(
        "requirement_item_shared_elements",
        "uq_item_shared_element_version",
        ["requirement_item_id", "shared_element_id", "version"],
    )
    _add_column_if_missing(
        "requirement_items",
        sa.Column("version", sa.Integer(), nullable=False, server_default=sa.text("1")),
    )
    _add_column_if_missing(
        "requirement_items",
        sa.Column("is_current", sa.Boolean(), nullable=False, server_default=sa.text("true")),
    )
    _add_column_if_missing("requirement_items", sa.Column("valid_from", sa.Date(), nullable=True))
    _add_column_if_missing("requirement_items", sa.Column("valid_to", sa.Date(), nullable=True))
    _create_index_if_missing(
        "requirement_items", op.f("ix_requirement_items_is_current"), ["is_current"]
    )
    if _has_index("role_bindings", op.f("uq_user_scope")):
        op.drop_index(op.f("uq_user_scope"), table_name="role_bindings")
    _create_unique_if_missing(
        "role_bindings", "uq_user_scope", ["user_id", "scope_type", "scope_id"]
    )
    _add_column_if_missing(
        "shared_elements",
        sa.Column("version", sa.Integer(), nullable=False, server_default=sa.text("1")),
    )
    _add_column_if_missing(
        "shared_elements",
        sa.Column("is_current", sa.Boolean(), nullable=False, server_default=sa.text("true")),
    )
    _add_column_if_missing("shared_elements", sa.Column("valid_from", sa.Date(), nullable=True))
    _add_column_if_missing("shared_elements", sa.Column("valid_to", sa.Date(), nullable=True))
    _create_index_if_missing(
        "shared_elements", op.f("ix_shared_elements_is_current"), ["is_current"]
    )
    _add_column_if_missing(
        "user_invitations", sa.Column("last_sent_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_invitations", "last_sent_at")
    op.drop_index(op.f("ix_shared_elements_is_current"), table_name="shared_elements")
    op.drop_column("shared_elements", "valid_to")
    op.drop_column("shared_elements", "valid_from")
    op.drop_column("shared_elements", "is_current")
    op.drop_column("shared_elements", "version")
    op.drop_constraint("uq_user_scope", "role_bindings", type_="unique")
    op.create_index(
        op.f("uq_user_scope"), "role_bindings", ["user_id", "scope_type", "scope_id"], unique=True
    )
    op.drop_index(op.f("ix_requirement_items_is_current"), table_name="requirement_items")
    op.drop_column("requirement_items", "valid_to")
    op.drop_column("requirement_items", "valid_from")
    op.drop_column("requirement_items", "is_current")
    op.drop_column("requirement_items", "version")
    op.drop_constraint(
        "uq_item_shared_element_version", "requirement_item_shared_elements", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_item_shared_element"),
        "requirement_item_shared_elements",
        ["requirement_item_id", "shared_element_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint(None, "reporting_projects", type_="foreignkey")
    op.drop_column("reporting_projects", "boundary_snapshot_id")
    op.drop_constraint(None, "refresh_tokens", type_="foreignkey")
    op.drop_column("notifications", "digest_sent_at")
    op.drop_column("notifications", "digest_sent")
    op.drop_index(op.f("ix_export_jobs_next_retry_at"), table_name="export_jobs")
    op.drop_column("export_jobs", "next_retry_at")
    op.drop_column("export_jobs", "max_attempts")
    op.drop_column("export_jobs", "attempt")
    op.drop_column("export_jobs", "artifact_encoding")
    op.drop_column("data_points", "calculation_rule_id")
    op.drop_column("data_points", "is_derived")
    op.drop_column("ai_interactions", "tools_used")
    op.drop_index(op.f("ix_data_point_versions_data_point_id"), table_name="data_point_versions")
    op.drop_table("data_point_versions")
    op.drop_index(op.f("ix_worker_leases_expires_at"), table_name="worker_leases")
    op.drop_table("worker_leases")
    op.drop_table("platform_settings")
    # ### end Alembic commands ###
